### ISSUE TITLE
组件化单独运行时出现Unable to instantiate activity ComponentInfo，请问知道原因吗

### ISSUE THREAD

**Issue by mackwu828** [Rabtman/AcgClub#14]
```
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.kdb.main/com.kdb.main.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.kdb.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/base.apk"],nativeLibraryDirectories=[/data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/lib/arm64, /data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kdb.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/base.apk"],nativeLibraryDirectories=[/data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/lib/arm64, /data/app/com.kdb.main-aBRAem4mAf4gsxqk71CGtw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1175)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821) 
```

**Comment by Rabtman** [comment]
后面不是还写了Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kdb.main.MainActivity"，我不清楚你进行了哪些修改。但是项目本身的组件可以单独运行没问题

**Comment by mackwu828** [comment]
![image](https://user-images.githubusercontent.com/31396243/55450317-49863900-5601-11e9-85d5-878e0aaa4bc8.png)


我是学着你的架构写了个 demo，单独运行这个组件跑不起来，直接闪退，不知道为啥

**Comment by Rabtman** [comment]
检查配置文件，善用搜索引擎
